# Generated by Django 4.0.5 on 2022-08-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_asistencia_vacaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='vacaciones',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='vacaciones_Fin',
            field=models.DateField(blank=True, help_text='Defina hasta que fecha desea vacaciones el próximo mes', null=True, verbose_name='Fecha de las futuras vacaciones'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='vacaciones_Inicio',
            field=models.DateField(blank=True, help_text='Defina a partir de que fecha desea vacaciones el próximo mes', null=True, verbose_name='Fecha de inicio de las futuras vacaciones'),
        ),
    ]
