# Generated by Django 4.0.5 on 2022-06-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_remove_asistencia_persona_alter_asistencia_autorizo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='vacaciones',
        ),
    ]
