# Generated by Django 4.0.5 on 2022-07-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('Sistemas', 'Sistemas'), ('Tesorería', 'Tesorería'), ('Crédito', 'Crédito'), ('Direción General', 'Dirección General'), ('Economía', 'Economía'), ('Negocio', 'Negocio'), ('Aseguramiento', 'Aseguramiento')], help_text='Seleccione a que área pertenece el documento', max_length=200, verbose_name='Categoría')),
                ('archivo', models.FileField(blank=True, help_text='Dirección del comprimido', max_length=50, null=True, upload_to='biblioteca/', verbose_name='Comprimido')),
            ],
            options={
                'verbose_name': 'Biblioteca',
                'verbose_name_plural': 'Bibliotecas',
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Nombre del documento de texto', max_length=50, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, help_text='Detalle una breve descripción del contenido de la Instrucción', max_length=200, null=True, verbose_name='Descripción')),
                ('anno', models.IntegerField(help_text='Año en que fue emitida', verbose_name='Año de emisión')),
                ('numero', models.IntegerField(help_text='Número que le corresponde', verbose_name='Número')),
                ('archivo', models.FileField(blank=True, help_text='Archivo a subir', max_length=50, null=True, upload_to='documentos/', verbose_name='Archivo')),
                ('organismo', models.CharField(help_text='Organismo Emisor', max_length=20, verbose_name='Organismo emisor')),
            ],
            options={
                'verbose_name': 'Circular',
                'verbose_name_plural': 'Circulares',
            },
        ),
        migrations.CreateModel(
            name='Instruc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Nombre del documento de texto', max_length=50, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, help_text='Detalle una breve descripción del contenido de la Instrucción', max_length=200, null=True, verbose_name='Descripción')),
                ('anno', models.IntegerField(help_text='Año en que fue emitida', verbose_name='Año de emisión')),
                ('numero', models.IntegerField(help_text='Número que le corresponde', verbose_name='Número')),
                ('archivo', models.FileField(blank=True, help_text='Archivo a subir', max_length=50, null=True, upload_to='documentos/', verbose_name='Archivo')),
                ('tipo', models.CharField(help_text='Tipo de Intrucción', max_length=50, verbose_name='Tipo de Instrucción')),
                ('anexo', models.CharField(help_text='Defina el nombre de los anexos', max_length=50, verbose_name='Anexo')),
                ('tema', models.CharField(choices=[('Crédito', 'Crédito'), ('Economía', 'Economía'), ('Tesorería', 'Tesorería')], help_text='Defina a que área esta asociado este Tema', max_length=200, verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Instrucción',
                'verbose_name_plural': 'Instrucciones',
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Nombre del documento de texto', max_length=50, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, help_text='Detalle una breve descripción del contenido de la Instrucción', max_length=200, null=True, verbose_name='Descripción')),
                ('anno', models.IntegerField(help_text='Año en que fue emitida', verbose_name='Año de emisión')),
                ('numero', models.IntegerField(help_text='Número que le corresponde', verbose_name='Número')),
                ('archivo', models.FileField(blank=True, help_text='Archivo a subir', max_length=50, null=True, upload_to='documentos/', verbose_name='Archivo')),
                ('seccion', models.IntegerField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('600', '600'), ('700', '700'), ('900', '900')], help_text='Defina la sección a la que pertenece', verbose_name='Sección')),
                ('grupo', models.CharField(help_text='Defina al grupo al que pertenece', max_length=200, verbose_name='Grupo')),
                ('subGrupo', models.CharField(help_text='Defina el subgrupo al que pertenece', max_length=50, verbose_name='Subgrupo')),
                ('anexo', models.CharField(help_text='Defina el nombre del anexo', max_length=50, verbose_name='Anexo')),
                ('proforma', models.CharField(help_text='Defina la proforma', max_length=50, verbose_name='Proforma')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
            },
        ),
    ]
