# Generated by Django 4.0.5 on 2022-06-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='seccion',
            field=models.IntegerField(help_text='Defina la sección a la que pertenece', verbose_name='Sección'),
        ),
    ]
