# Generated by Django 4.0.5 on 2022-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblioteca',
            options={'verbose_name': 'Biblioteca', 'verbose_name_plural': 'Bibliotecas'},
        ),
        migrations.AlterModelOptions(
            name='circular',
            options={'verbose_name': 'Circular', 'verbose_name_plural': 'Circulares'},
        ),
        migrations.AlterModelOptions(
            name='instruc',
            options={'verbose_name': 'Instrucción', 'verbose_name_plural': 'Instrucciones'},
        ),
        migrations.AlterModelOptions(
            name='procedimiento',
            options={'verbose_name': 'Procedimiento', 'verbose_name_plural': 'Procedimientos'},
        ),
        migrations.AlterField(
            model_name='circular',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre del documento de texto', max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='instruc',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre del documento de texto', max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre del documento de texto', max_length=50, verbose_name='Título'),
        ),
    ]
