# Generated by Django 4.0.5 on 2022-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_alter_procedimiento_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='seccion',
            field=models.IntegerField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('600', '600'), ('700', '700'), ('900', '900')], help_text='Defina la sección a la que pertenece', verbose_name='Sección'),
        ),
    ]
