# Generated by Django 4.0.5 on 2022-06-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_alter_biblioteca_options_alter_circular_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='categoria',
            field=models.CharField(choices=[('Sistemas', 'Sistemas'), ('Tesorería', 'Tesorería'), ('Crédito', 'Crédito'), ('Direción General', 'Dirección General'), ('Economía', 'Economía'), ('Negocio', 'Negocio'), ('Aseguramiento', 'Aseguramiento')], help_text='Seleccione a que área pertenece el documento', max_length=200, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='instruc',
            name='tema',
            field=models.CharField(choices=[('Crédito', 'Crédito'), ('Economía', 'Economía'), ('Tesorerí', 'Tesorería')], help_text='Defina a que área esta asociado este Tema', max_length=200, verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='grupo',
            field=models.CharField(help_text='Defina al grupo al que pertenece', max_length=200, verbose_name='Grupo'),
        ),
    ]
