# Generated by Django 4.0.5 on 2022-06-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0003_alter_biblioteca_categoria_alter_instruc_tema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruc',
            name='tema',
            field=models.CharField(choices=[('Crédito', 'Crédito'), ('Economía', 'Economía'), ('Tesorería', 'Tesorería')], help_text='Defina a que área esta asociado este Tema', max_length=200, verbose_name='Tema'),
        ),
    ]
